/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_APB2ENR   (*(volatile uint32_t *)0x40021018U)
#define GPIOC_CRH     (*(volatile uint32_t *)0x40011004U)
#define GPIOC_BSRR    (*(volatile uint32_t *)0x40011010U)

#define RCC_IOPCEN    (1U << 4)
#define GPIO_CRH_MODE13_Pos 20U
#define GPIO_CRH_CNF13_Pos  22U
#define GPIO_BSRR_BS13      (1U << 13)
#define GPIO_BSRR_BR13      (1U << 29)

static void delay(volatile uint32_t count)
{
  while (count-- != 0U)
  {
    __asm volatile ("nop");
  }
}

int main(void)
{
  RCC_APB2ENR |= RCC_IOPCEN;

  GPIOC_CRH &= ~((3U << GPIO_CRH_MODE13_Pos) | (3U << GPIO_CRH_CNF13_Pos));
  GPIOC_CRH |= (2U << GPIO_CRH_MODE13_Pos);

  for (;;)
  {
    GPIOC_BSRR = GPIO_BSRR_BR13;
    delay(500000U);

    GPIOC_BSRR = GPIO_BSRR_BS13;
    delay(500000U);
  }
}
