/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define GPIOC_BASE 0x40011000UL
#define RCC_BASE   0x40021000UL

#define RCC_APB2ENR 	(*(volatile uint32_t *)(RCC_BASE + 0x18))
#define GPIOC_CRH       (*(volatile uint32_t *)(GPIOC_BASE + 0x04))
#define GPIOC_ODR       (*(volatile uint32_t *)(GPIOC_BASE + 0x0C))
#define GPIOC_BSRR      (*(volatile uint32_t *)(GPIOC_BASE + 0x10))


void delay(volatile uint32_t count) {
    while (count--) {
        __asm("nop");
    }
}

int main(void) {
    // 1. Enable GPIOC Clock (Bit 4)
    RCC_APB2ENR |= (1 << 4);

    // 2. Configure PC13 as Output Push-Pull, 2 MHz
    // Clear bits 23:20 first, then write 0b0010 (0x2)
    GPIOC_CRH &= ~(0xFU << 20);
    GPIOC_CRH |=  (0x2U << 20);

    while (1) {
        // Turn LED ON (PC13 LOW) via BSRR Bit 29 (BR13)
        GPIOC_BSRR = (1 << 29);
//        GPIOC_ODR &= ~(1<<13);
        delay(500000);

        // Turn LED OFF (PC13 HIGH) via BSRR Bit 13 (BS13)
        GPIOC_BSRR = (1 << 13);
//        GPIOC_ODR |= (1<<13);
        delay(500000);
    }

    return 0;
}
