/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// ----------------------------------------------------------------------------
// 1. Memory Map and Register Addresses
// ----------------------------------------------------------------------------
#define RCC_APB2ENR   (*(volatile uint32_t *)0x40021018U)
#define RCC_APB1ENR   (*(volatile uint32_t *)0x4002101CU)

#define GPIOB_CRL     (*(volatile uint32_t *)0x40010C00U)

#define I2C1_CR1      (*(volatile uint32_t *)0x40005400U)
#define I2C1_CR2      (*(volatile uint32_t *)0x40005404U)
#define I2C1_DR       (*(volatile uint32_t *)0x40005410U)
#define I2C1_SR1      (*(volatile uint32_t *)0x40005414U)
#define I2C1_SR2      (*(volatile uint32_t *)0x40005418U)
#define I2C1_CCR      (*(volatile uint32_t *)0x4000541CU)
#define I2C1_TRISE    (*(volatile uint32_t *)0x40005420U)

// ----------------------------------------------------------------------------
// 2. Bit Masks
// ----------------------------------------------------------------------------
#define RCC_IOPBEN      (1U << 3)
#define RCC_I2C1EN      (1U << 21)

#define I2C_CR1_PE      (1U << 0)
#define I2C_CR1_START   (1U << 8)
#define I2C_CR1_STOP    (1U << 9)
#define I2C_CR1_ACK     (1U << 10)
#define I2C_CR1_SWRST   (1U << 15)

#define I2C_SR1_SB      (1U << 0)
#define I2C_SR1_ADDR    (1U << 1)
#define I2C_SR1_TXE     (1U << 7)
#define I2C_SR1_BTF     (1U << 2)

#define SSD1306_I2C_ADDR 0x78U

// ----------------------------------------------------------------------------
// 3. Utility Functions
// ----------------------------------------------------------------------------
static void Delay(volatile uint32_t count)
{
    while (count--) { __asm volatile ("nop"); }
}

void I2C1_Init(void)
{
    RCC_APB2ENR |= RCC_IOPBEN;
    RCC_APB1ENR |= RCC_I2C1EN;

    // PB6 and PB7 as AF Open-Drain, 50 MHz
    GPIOB_CRL &= ~(0xFFU << 24);
    GPIOB_CRL |=  (0xFFU << 24);

    I2C1_CR1 |= I2C_CR1_SWRST;
    I2C1_CR1 &= ~I2C_CR1_SWRST;

    I2C1_CR2 = 8U;
    I2C1_CCR = 40U;
    I2C1_TRISE = 9U;
    I2C1_CR1 |= I2C_CR1_PE;
}

void I2C1_Start(void)
{
    I2C1_CR1 |= I2C_CR1_START;
    while (!(I2C1_SR1 & I2C_SR1_SB));
}

void I2C1_SendAddress(uint8_t addr)
{
    I2C1_DR = addr;
    while (!(I2C1_SR1 & I2C_SR1_ADDR));
    volatile uint32_t temp = I2C1_SR1;
    temp = I2C1_SR2;
    (void)temp;
}

void I2C1_WriteData(uint8_t data)
{
    while (!(I2C1_SR1 & I2C_SR1_TXE));
    I2C1_DR = data;
    while (!(I2C1_SR1 & I2C_SR1_BTF));
}

void I2C1_Stop(void)
{
    I2C1_CR1 |= I2C_CR1_STOP;
}

// ----------------------------------------------------------------------------
// 4. SSD1306 Commands
// ----------------------------------------------------------------------------
static void SSD1306_WriteCommand(uint8_t command)
{
    I2C1_Start();
    I2C1_SendAddress(SSD1306_I2C_ADDR);
    I2C1_WriteData(0x00U);
    I2C1_WriteData(command);
    I2C1_Stop();
}

static void SSD1306_WriteDataByte(uint8_t data)
{
    I2C1_Start();
    I2C1_SendAddress(SSD1306_I2C_ADDR);
    I2C1_WriteData(0x40U);
    I2C1_WriteData(data);
    I2C1_Stop();
}

static void SSD1306_SetCursor(uint8_t page, uint8_t column)
{
    SSD1306_WriteCommand(0xB0U | (page & 0x07U));
    SSD1306_WriteCommand(0x00U | (column & 0x0FU));
    SSD1306_WriteCommand(0x10U | ((column >> 4) & 0x0FU));
}

static void SSD1306_Init(void)
{
    SSD1306_WriteCommand(0xAEU); // Display off
    SSD1306_WriteCommand(0xD5U); SSD1306_WriteCommand(0x80U); // Clock divide
    SSD1306_WriteCommand(0xA8U); SSD1306_WriteCommand(0x3FU); // Multiplex 1/64
    SSD1306_WriteCommand(0xD3U); SSD1306_WriteCommand(0x00U); // Display offset
    SSD1306_WriteCommand(0x40U); // Start line = 0
    SSD1306_WriteCommand(0x8DU); SSD1306_WriteCommand(0x14U); // Charge pump
    SSD1306_WriteCommand(0x20U); SSD1306_WriteCommand(0x00U); // Horizontal addressing
    SSD1306_WriteCommand(0xA1U); // Segment remap
    SSD1306_WriteCommand(0xC8U); // COM scan dec
    SSD1306_WriteCommand(0xDAU); SSD1306_WriteCommand(0x12U); // COM pins
    SSD1306_WriteCommand(0x81U); SSD1306_WriteCommand(0x7FU); // Contrast
    SSD1306_WriteCommand(0xD9U); SSD1306_WriteCommand(0xF1U); // Pre-charge
    SSD1306_WriteCommand(0xDBU); SSD1306_WriteCommand(0x40U); // VCOM detect
    SSD1306_WriteCommand(0xA4U); // Resume RAM content display
    SSD1306_WriteCommand(0xA6U); // Normal display
    SSD1306_WriteCommand(0x2EU); // Deactivate scroll
    SSD1306_WriteCommand(0xAFU); // Display on
}

static const uint8_t welcomeFont[][5] = {
    // W, E, L, C, O, M
    { 0x81U, 0x81U, 0x92U, 0xAAU, 0x44U }, // W
    { 0xFFU, 0x89U, 0x89U, 0x89U, 0x81U }, // E
    { 0xFFU, 0x01U, 0x01U, 0x01U, 0x01U }, // L
    { 0x7EU, 0x81U, 0x81U, 0x81U, 0x42U }, // C
    { 0x7EU, 0x81U, 0x81U, 0x81U, 0x7EU }, // O
    { 0xFFU, 0x18U, 0x24U, 0x18U, 0xFFU }, // M
};

static void SSD1306_WriteChar(char c)
{
    const uint8_t *glyph = 0;

    switch (c) {
    case 'W': glyph = welcomeFont[0]; break;
    case 'E': glyph = welcomeFont[1]; break;
    case 'L': glyph = welcomeFont[2]; break;
    case 'C': glyph = welcomeFont[3]; break;
    case 'O': glyph = welcomeFont[4]; break;
    case 'M': glyph = welcomeFont[5]; break;
    default:
        SSD1306_WriteDataByte(0x00U);
        return;
    }

    for (uint8_t i = 0U; i < 5U; i++) {
        SSD1306_WriteDataByte(glyph[i]);
    }
    SSD1306_WriteDataByte(0x00U);
}

static uint8_t SSD1306_StringWidth(const char *str)
{
    uint8_t width = 0U;
    while (*str != '\0') {
        width += 6U; // 5 pixel columns + 1 pixel spacing
        str++;
    }
    return width;
}

static void SSD1306_WriteString(const char *str)
{
    while (*str != '\0') {
        SSD1306_WriteChar(*str++);
    }
}

static void SSD1306_WriteStringCentered(uint8_t page, const char *str)
{
    uint8_t textWidth = SSD1306_StringWidth(str);
    uint8_t startColumn = (128U - textWidth) / 2U;
    SSD1306_SetCursor(page, startColumn);
    SSD1306_WriteString(str);
}

static void SSD1306_Clear(void)
{
    for (uint8_t page = 0U; page < 8U; page++) {
        SSD1306_SetCursor(page, 0U);
        for (uint8_t col = 0U; col < 128U; col++) {
            SSD1306_WriteDataByte(0x00U);
        }
    }
}

int main(void)
{
    I2C1_Init();
    Delay(100000U);
    SSD1306_Init();
    SSD1306_Clear();

    SSD1306_WriteStringCentered(3U, "WELCOME");

    while (1) {
        // Nothing else needed in the main loop for this demo.
    }
}
