/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include <stdint.h>

#include "adc.h"
#include "capstone_platform.h"
#include "i2c.h"
#include "ssd1306.h"
#include "tx_api.h"
#include "tx_initialize.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RTOS_TICK_RATE_HZ            1000U
#define BLINK_THREAD_STACK_SIZE      512U
#define DATA_THREAD_STACK_SIZE       1024U
#define MONITOR_THREAD_STACK_SIZE    512U
#define SENSOR_SAMPLE_DELAY_TICKS    20U
#define ALERT_BLINK_DELAY_TICKS      100U
#define ALERT_HOLD_TICKS             20U
#define SENSOR_RING_SIZE             64U
#define MONITOR_DELAY_CYCLES         400000U
#define MONITOR_STALL_THRESHOLD      3U

static TX_THREAD blink_thread;
static TX_THREAD data_sensor_thread;
static TX_THREAD monitor_thread;
static TX_SEMAPHORE button_alert_semaphore;
static TX_MUTEX uart_mutex;
static TX_MUTEX oled_mutex;

static ULONG blink_thread_stack[BLINK_THREAD_STACK_SIZE / sizeof(ULONG)];
static ULONG data_sensor_thread_stack[DATA_THREAD_STACK_SIZE / sizeof(ULONG)];
static ULONG monitor_thread_stack[MONITOR_THREAD_STACK_SIZE / sizeof(ULONG)];

static volatile ULONG blink_count;
static volatile ULONG sensor_loop_count;
static volatile ULONG sensor_sample;
static volatile ULONG sensor_average;
static volatile uint8_t button_pressed;
static volatile uint8_t button_state;
static volatile ULONG alert_ticks_remaining;
static uint16_t sensor_ring_buffer[SENSOR_RING_SIZE];
static uint32_t sensor_ring_sum;
static uint8_t sensor_ring_head;
static uint8_t sensor_ring_count;

extern volatile ULONG _tx_timer_system_clock;
extern TX_THREAD _tx_timer_thread;
extern uint8_t _end;

static UINT uart_try_lock(void)
{
  if (tx_thread_identify() == TX_NULL)
  {
    return TX_SUCCESS;
  }

  return tx_mutex_get(&uart_mutex, TX_NO_WAIT);
}

static void uart_lock(void)
{
  if (tx_thread_identify() != TX_NULL)
  {
    (void)tx_mutex_get(&uart_mutex, TX_WAIT_FOREVER);
  }
}

static void uart_unlock(void)
{
  if (tx_thread_identify() != TX_NULL)
  {
    (void)tx_mutex_put(&uart_mutex);
  }
}

static void uart_send_string_locked(const char *str)
{
  uart_lock();
  usart1_send_string(str);
  uart_unlock();
}

static void usart1_send_monitor_snapshot(void)
{
  usart1_send_string("MON tick=");
  usart1_send_uint32((uint32_t)_tx_timer_system_clock);
  usart1_send_string(" loops=");
  usart1_send_uint32((uint32_t)sensor_loop_count);
  usart1_send_string(" s=");
  usart1_send_uint32((uint32_t)data_sensor_thread.tx_thread_state);
  usart1_send_string(" tt=");
  usart1_send_uint32((uint32_t)_tx_timer_thread.tx_thread_state);
  usart1_send_string(" blink=");
  usart1_send_uint32((uint32_t)blink_count);
  usart1_send_string(" avg=");
  usart1_send_uint32((uint32_t)sensor_average);
  usart1_send_string("\r\n");
}

static void sensor_buffer_push(uint16_t sample)
{
  if (sensor_ring_count < SENSOR_RING_SIZE)
  {
    sensor_ring_buffer[sensor_ring_head] = sample;
    sensor_ring_sum += sample;
    sensor_ring_count++;
  }
  else
  {
    sensor_ring_sum -= sensor_ring_buffer[sensor_ring_head];
    sensor_ring_buffer[sensor_ring_head] = sample;
    sensor_ring_sum += sample;
  }

  sensor_ring_head++;
  if (sensor_ring_head >= SENSOR_RING_SIZE)
  {
    sensor_ring_head = 0U;
  }

  sensor_sample = sample;
  sensor_average = sensor_ring_sum / ((sensor_ring_count == 0U) ? 1U : sensor_ring_count);
}

static uint32_t get_hclk_frequency(void)
{
  uint32_t cfgr = RCC_CFGR;
  uint32_t sysclk_source = (cfgr >> 2) & 0x3U;
  uint32_t sysclk_hz;
  uint32_t hpre;

  switch (sysclk_source)
  {
    case 0U:
      sysclk_hz = 8000000U;
      break;
    case 1U:
      sysclk_hz = 8000000U;
      break;
    case 2U:
    {
      uint32_t pllmul = ((cfgr >> 18) & 0xFU) + 2U;
      uint32_t pllsrc = (cfgr >> 16) & 0x1U;
      uint32_t pllxtpre = (cfgr >> 17) & 0x1U;
      uint32_t pll_input_hz = 8000000U;

      if (pllsrc != 0U)
      {
        pll_input_hz = (pllxtpre != 0U) ? 4000000U : 8000000U;
      }

      sysclk_hz = pll_input_hz * pllmul;
      break;
    }
    default:
      sysclk_hz = 8000000U;
      break;
  }

  hpre = (cfgr >> 4) & 0xFU;
  if (hpre < 8U)
  {
    return sysclk_hz;
  }

  switch (hpre)
  {
    case 8U: return sysclk_hz / 2U;
    case 9U: return sysclk_hz / 4U;
    case 10U: return sysclk_hz / 8U;
    case 11U: return sysclk_hz / 16U;
    case 12U: return sysclk_hz / 64U;
    case 13U: return sysclk_hz / 128U;
    case 14U: return sysclk_hz / 256U;
    case 15U: return sysclk_hz / 512U;
    default: return sysclk_hz;
  }
}

static void bluepill_led_init(void)
{
  RCC_APB2ENR |= RCC_IOPCEN;
  GPIOC_CRH &= ~(GPIO_CRH_MODE13_MASK | GPIO_CRH_CNF13_MASK);
  GPIOC_CRH |= (2UL << GPIO_CRH_MODE13_Pos);
  GPIOC_ODR |= GPIO_ODR_PIN13;
}

static void systick_init(void)
{
  uint32_t hclk = get_hclk_frequency();
  uint32_t reload = (hclk / RTOS_TICK_RATE_HZ) - 1U;

  SYSTICK_CTRL = 0U;
  SCB_SHPR3 = (SCB_SHPR3 & 0x0000FFFFUL) | SCB_SHPR3_PENDSV_LOWEST | SCB_SHPR3_SYSTICK_LOWEST;
  SYSTICK_LOAD = reload;
  SYSTICK_VAL = 0U;
  SYSTICK_CTRL = SYSTICK_CTRL_CLKSOURCE | SYSTICK_CTRL_TICKINT | SYSTICK_CTRL_ENABLE;
  __asm volatile ("cpsie i");
}

static void oled_render_dashboard(void)
{
  if (tx_mutex_get(&oled_mutex, TX_NO_WAIT) != TX_SUCCESS)
  {
    return;
  }

  (void)ssd1306_render_dashboard((uint16_t)sensor_sample,
                                 (uint16_t)sensor_average,
                                 button_state,
                                 (alert_ticks_remaining > 0U) ? 1U : 0U,
                                 sensor_ring_buffer,
                                 SENSOR_RING_SIZE,
                                 sensor_ring_head,
                                 sensor_ring_count);

  (void)tx_mutex_put(&oled_mutex);
}

static void data_sensor_peripherals_init(void)
{
  usart1_init();
  uart_send_string_locked("USART1 ready\r\n");

  adc_init();

  RCC_APB2ENR |= RCC_IOPAEN;
  GPIOA_CRL &= ~(0xFUL << 4);
  GPIOA_CRL |= (0x8UL << 4);
  GPIOA_ODR |= (1UL << 1);

  i2c1_init();
  delay_cycles(100000U);
  ssd1306_init();

  if (ssd1306_is_ready() != 0U)
  {
    uart_send_string_locked("SSD1306 ready\r\n");
  }
  else
  {
    uart_send_string_locked("SSD1306 not detected\r\n");
  }

  uart_send_string_locked("Sensor thread ready\r\n");
}

VOID _tx_initialize_low_level(VOID)
{
  _tx_initialize_unused_memory = &_end;
  systick_init();
}

static VOID blink_thread_entry(ULONG thread_input)
{
  (void)thread_input;

  for (;;)
  {
    (void)tx_semaphore_get(&button_alert_semaphore, TX_WAIT_FOREVER);

    alert_ticks_remaining = ALERT_HOLD_TICKS;
    oled_render_dashboard();

    GPIOC_BSRR = (1UL << 29);
    tx_thread_sleep(ALERT_BLINK_DELAY_TICKS);
    GPIOC_BSRR = GPIO_BSRR_BS13;
    tx_thread_sleep(ALERT_BLINK_DELAY_TICKS);
    GPIOC_BSRR = (1UL << 29);
    tx_thread_sleep(ALERT_BLINK_DELAY_TICKS);
    GPIOC_BSRR = GPIO_BSRR_BS13;

    blink_count++;
  }
}

static VOID monitor_thread_entry(ULONG thread_input)
{
  ULONG last_sensor_loops = 0U;
  ULONG stalled_count = 0U;
  UINT stall_reported = TX_FALSE;

  (void)thread_input;

  uart_send_string_locked("Monitor thread ready\r\n");

  for (;;)
  {
    if (sensor_loop_count == last_sensor_loops)
    {
      stalled_count++;
      if ((stalled_count >= MONITOR_STALL_THRESHOLD) &&
          (stall_reported == TX_FALSE) &&
          (uart_try_lock() == TX_SUCCESS))
      {
        usart1_send_string("MON stalled ");
        usart1_send_monitor_snapshot();
        uart_unlock();
        stall_reported = TX_TRUE;
      }
    }
    else
    {
      last_sensor_loops = sensor_loop_count;
      stalled_count = 0U;
      stall_reported = TX_FALSE;
    }

    delay_cycles(MONITOR_DELAY_CYCLES);
  }
}

static VOID data_sensor_thread_entry(ULONG thread_input)
{
  char received_char;
  uint16_t sample;
  uint8_t button_previous = 1U;

  (void)thread_input;

  data_sensor_peripherals_init();

  for (;;)
  {
    sensor_loop_count++;
    sample = adc_read_sample();
    sensor_buffer_push(sample);

    {
      uint8_t button_current = ((GPIOA_IDR & (1UL << 1)) != 0U) ? 1U : 0U;
      if ((button_previous == 1U) && (button_current == 0U))
      {
        button_pressed = 1U;
      }
      button_previous = button_current;
    }

    if (button_pressed != 0U)
    {
      button_pressed = 0U;
      button_state ^= 1U;
      uart_send_string_locked("Button pressed\r\n");
      (void)tx_semaphore_put(&button_alert_semaphore);
    }

    if (uart_try_lock() == TX_SUCCESS)
    {
      usart1_send_string("ADC: ");
      usart1_send_uint32(sensor_sample);
      usart1_send_string(" AVG: ");
      usart1_send_uint32(sensor_average);
      usart1_send_string("\r\n");
      uart_unlock();
    }

    if (usart1_data_available() != 0U)
    {
      received_char = usart1_receive_char();
      if (uart_try_lock() == TX_SUCCESS)
      {
        usart1_send_string("Received: ");
        usart1_send_char(received_char);
        usart1_send_string("\r\n");
        uart_unlock();
      }
    }

    oled_render_dashboard();

    if (alert_ticks_remaining > 0U)
    {
      alert_ticks_remaining--;
    }

    tx_thread_sleep(SENSOR_SAMPLE_DELAY_TICKS);
  }
}

void ADC1_2_IRQHandler(void)
{
}

void SystemInit(void)
{
}

void tx_application_define(void *first_unused_memory)
{
  (void)first_unused_memory;

  (void)tx_semaphore_create(&button_alert_semaphore, "ButtonAlert", 0U);
  (void)tx_mutex_create(&uart_mutex, "UartMutex", TX_NO_INHERIT);
  (void)tx_mutex_create(&oled_mutex, "OledMutex", TX_NO_INHERIT);

  tx_thread_create(&blink_thread,
                   "Blink Thread",
                   blink_thread_entry,
                   0U,
                   blink_thread_stack,
                   sizeof(blink_thread_stack),
                   1U,
                   1U,
                   TX_NO_TIME_SLICE,
                   TX_AUTO_START);

  tx_thread_create(&data_sensor_thread,
                   "Data Sensor Thread",
                   data_sensor_thread_entry,
                   0U,
                   data_sensor_thread_stack,
                   sizeof(data_sensor_thread_stack),
                   2U,
                   2U,
                   TX_NO_TIME_SLICE,
                   TX_AUTO_START);

  tx_thread_create(&monitor_thread,
                   "Monitor Thread",
                   monitor_thread_entry,
                   0U,
                   monitor_thread_stack,
                   sizeof(monitor_thread_stack),
                   3U,
                   3U,
                   TX_NO_TIME_SLICE,
                   TX_AUTO_START);
}

int main(void)
{
  bluepill_led_init();
  tx_kernel_enter();

  while (1)
  {
  }
}
